---
name: Check Point CloudGuard Assessment
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions: write-all

jobs:
  Spectral_scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Sarif results to Github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: output.sarif
